import Admin from './sidebar/page'
import './globals.css'
import './layout.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='sidebar-layout'>
          <Admin/>
        </div>
        <div className='main-content'>
          {children}
        </div>
        
      </body>
    </html>
  )
}
